version: '3'
services:
  web:
    build: .
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
  postgres:
    image: "postgres:16.2"
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    volumes:
      - .:/db
